// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdd9tPdbE6TBo-BkrPlY5FyyShK5Foi3c',
    appId: '1:887515720483:web:bcfb35221385a948f4ba96',
    messagingSenderId: '887515720483',
    projectId: 'safespace-cec3e',
    authDomain: 'safespace-cec3e.firebaseapp.com',
    storageBucket: 'safespace-cec3e.appspot.com',
    measurementId: 'G-FQC1YKX12J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgI_Dq9Q6XZE9EvTZjPfv0qplKaZBa3Y',
    appId: '1:887515720483:android:6fb793e136dd0282f4ba96',
    messagingSenderId: '887515720483',
    projectId: 'safespace-cec3e',
    storageBucket: 'safespace-cec3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfO5VG7IPFobHtAueLFSa8YVGQIP3NVxE',
    appId: '1:887515720483:ios:24d85e7afae7e2a9f4ba96',
    messagingSenderId: '887515720483',
    projectId: 'safespace-cec3e',
    storageBucket: 'safespace-cec3e.appspot.com',
    iosClientId: '887515720483-op8iiqhlrq5c6eb3alk8j89ei9v6pm3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.safespace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfO5VG7IPFobHtAueLFSa8YVGQIP3NVxE',
    appId: '1:887515720483:ios:24d85e7afae7e2a9f4ba96',
    messagingSenderId: '887515720483',
    projectId: 'safespace-cec3e',
    storageBucket: 'safespace-cec3e.appspot.com',
    iosClientId: '887515720483-op8iiqhlrq5c6eb3alk8j89ei9v6pm3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.safespace',
  );
}
